In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

In [2]:
#ques1
from sklearn.datasets import load_digits

In [3]:
digit=load_digits()
x=digit.data
y=digit.target
x.shape,y.shape

((1797, 64), (1797,))

In [4]:
#ques2
from sklearn.preprocessing import StandardScaler
x_std= StandardScaler().fit_transform(x)
x_std

array([[ 0.        , -0.33501649, -0.04308102, ..., -1.14664746,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  0.54856067,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  1.56568555,
         1.6951369 , -0.19600752],
       ...,
       [ 0.        , -0.33501649, -0.88456568, ..., -0.12952258,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.67419451, ...,  0.8876023 ,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649,  1.00877481, ...,  0.8876023 ,
        -0.26113572, -0.19600752]])

In [5]:
#ques4
from sklearn.decomposition import PCA
pca=PCA(n_components=8)
pca.fit(x_std)

PCA(copy=True, iterated_power='auto', n_components=8, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [6]:
principalComponents=pca.fit_transform(x_std)
principalComponents

array([[ 1.9141045 , -0.95448286, -3.94556928, ...,  0.53311458,
        -1.43041108,  1.49860486],
       [ 0.58934195,  0.92391296,  3.92461828, ..., -0.67330504,
         1.90590154,  0.59943073],
       [ 1.30219728, -0.31710521,  3.02295566, ...,  0.92310821,
        -1.28531065,  1.14388685],
       ...,
       [ 1.0219665 , -0.14720146,  2.46999998, ...,  0.00873622,
         0.27077955,  0.40829761],
       [ 1.07557741, -0.38013564, -2.45567197, ..., -0.61199018,
         0.95602458,  0.64578252],
       [-1.25833977, -2.22647231,  0.28313553, ...,  2.34975089,
        -0.49467122, -1.35996097]])

In [7]:
principalDf=pd.DataFrame(data=principalComponents,columns=['principal component=1','principal component=2','principal component=3','principal component=4','principal component=5','principal component=6','principal component=7','principal component=8'])
principalDf
#new x

principal component=1  principal component=2  principal component=3  \
0                  1.914105              -0.954483              -3.945569   
1                  0.589342               0.923913               3.924618   
2                  1.302197              -0.317105               3.022956   
3                 -3.020564              -0.869251              -0.801655   
4                  4.528926              -1.093774               0.973710   
5                 -1.302291              -1.147686              -1.575056   
6                  1.433984              -2.957586               2.831939   
7                  0.614196               5.462423               0.658322   
8                 -1.098895              -0.665249              -0.041181   
9                 -0.538536              -0.776760              -1.569762   
10                 3.378707              -0.495562              -2.279768   
11                 2.063273               2.016720               1.540304   
12                -1.937128              -1.815159               2.800992   
13                -3.258320               2.149291              -1.615250   
14                 5.458563               0.025170               0.182736   
15                -3.876782               2.606698               1.858818   
16                 0.921583              -3.262301               3.401919   
17                 1.415202               1.954819               0.560366   
18                -0.926224               2.252562               1.533468   
19                -2.370539              -2.932329              -0.381303   
20                 2.001672              -1.319339              -2.570659   
21                 1.694942               2.075300               0.885556   
22                -3.114477              -1.059126               2.451040   
23                -1.469766               3.910440              -2.077622   
24                 4.003117              -0.322070               0.587856   
25                -0.376750               0.525051               1.356161   
26                 1.286577              -3.969117               2.543139   
27                 3.842054               3.478538              -1.568659   
28                -0.167158               0.934761               1.259133   
29                -2.014346              -2.376621              -0.708172   
...                     ...                    ...                    ...   
1767               4.958675              -1.159720               0.645944   
1768               1.009142              -3.325977              -0.583973   
1769              -0.542620              -0.493257              -3.138920   
1770              -3.314606               1.510407              -0.819677   
1771               2.127900              -2.821846               3.623717   
1772              -1.814302               1.198271              -3.114237   
1773               1.374424              -4.417352               0.544520   
1774               0.762464               0.644245               3.118762   
1775              -0.432776               3.216241               2.011550   
1776              -0.526124              -1.154035              -1.889833   
1777               5.106785              -0.289512               0.341622   
1778               5.901303              -1.711288               1.856952   
1779               1.597123               4.676337               0.469972   
1780              -5.138159              -0.190857               2.223411   
1781              -1.416375              -1.030804               1.196188   
1782              -4.273397              -1.355667               3.058713   
1783              -3.137269              -1.411614               2.238088   
1784               1.568645              -0.438516              -1.840241   
1785               0.058384               1.978465               1.807504   
1786              -0.711571               0.253570              -2.934972   
17

In [8]:
pca.explained_variance_ratio_

array([0.12033916, 0.09561054, 0.08444414, 0.06498393, 0.04860096,
       0.04214027, 0.03939539, 0.03386923])

In [9]:
#ques3
principalDf_train,principalDf_test,y_train,y_test = train_test_split(principalDf,y,test_size = 0.3)

In [10]:
#ques5
reg = LogisticRegression()
reg.fit(principalDf_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [11]:
pred = reg.predict(principalDf_test)
pred

array([3, 3, 9, 7, 5, 2, 5, 2, 4, 2, 2, 1, 7, 6, 6, 7, 1, 6, 2, 9, 1, 8,
       9, 2, 5, 9, 9, 9, 2, 3, 0, 2, 0, 7, 9, 9, 3, 9, 2, 5, 0, 9, 4, 1,
       7, 2, 3, 7, 7, 0, 7, 3, 5, 2, 9, 7, 6, 5, 6, 6, 2, 8, 4, 3, 1, 1,
       1, 1, 2, 9, 6, 7, 7, 6, 5, 1, 5, 5, 8, 6, 0, 2, 2, 6, 9, 5, 0, 8,
       4, 5, 0, 0, 2, 2, 0, 1, 5, 5, 0, 0, 2, 3, 7, 2, 7, 7, 5, 9, 7, 0,
       1, 5, 0, 9, 0, 5, 3, 4, 7, 0, 2, 6, 7, 9, 4, 5, 3, 1, 9, 2, 2, 3,
       4, 9, 5, 6, 7, 4, 9, 1, 1, 0, 2, 4, 6, 5, 7, 8, 7, 3, 0, 8, 9, 1,
       7, 7, 9, 5, 1, 9, 2, 4, 9, 0, 0, 2, 3, 3, 2, 6, 3, 8, 5, 0, 7, 4,
       6, 9, 7, 5, 1, 4, 7, 3, 1, 3, 4, 3, 4, 1, 9, 6, 0, 0, 9, 2, 2, 3,
       0, 6, 1, 1, 7, 9, 2, 5, 6, 2, 0, 8, 2, 0, 1, 6, 4, 2, 2, 0, 9, 5,
       5, 3, 2, 1, 3, 6, 3, 7, 2, 5, 6, 3, 4, 3, 2, 0, 2, 0, 4, 2, 2, 3,
       5, 6, 0, 6, 7, 0, 7, 3, 5, 1, 2, 1, 5, 2, 5, 1, 8, 1, 0, 5, 5, 0,
       5, 5, 5, 4, 7, 1, 6, 9, 1, 7, 6, 1, 8, 0, 9, 1, 4, 4, 7, 9, 1, 3,
       4, 1, 1, 3, 2, 1, 2, 7, 4, 6, 3, 0, 7, 5, 3,

In [12]:
#ques6(a)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred)

0.8814814814814815

In [13]:
#ques6(b)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred)

array([[53,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 44,  1,  0,  1,  1,  0,  1,  2,  2],
       [ 0,  0, 57,  0,  0,  0,  0,  0,  2,  0],
       [ 0,  1,  0, 47,  0,  0,  0,  1,  2,  7],
       [ 0,  1,  0,  0, 46,  0,  0,  3,  0,  0],
       [ 0,  1,  0,  0,  0, 55,  1,  0,  0,  2],
       [ 1,  1,  0,  0,  0,  0, 54,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 56,  0,  0],
       [ 0,  6,  5,  3,  0,  2,  1,  1, 27,  6],
       [ 0,  1,  0,  5,  1,  0,  0,  1,  1, 37]], dtype=int64)

In [14]:
#ques6(c)
from sklearn.metrics import classification_report
print(classification_report(y_test,pred))

             precision    recall  f1-score   support

          0       0.98      1.00      0.99        53
          1       0.80      0.85      0.82        52
          2       0.90      0.97      0.93        59
          3       0.85      0.81      0.83        58
          4       0.96      0.92      0.94        50
          5       0.95      0.93      0.94        59
          6       0.96      0.96      0.96        56
          7       0.89      1.00      0.94        56
          8       0.79      0.53      0.64        51
          9       0.69      0.80      0.74        46

avg / total       0.88      0.88      0.88       540

