In [2]:
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
from sklearn import datasets
from sklearn import metrics
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

In [3]:
#question1
from sklearn.datasets import load_digits

In [4]:
digit=load_digits()
x=digit.data
y=digit.target
x.shape

(1797, 64)

In [5]:
#question2
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)

In [6]:
#ques3(a)
model=SVC()

In [7]:
model.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [8]:
pred=model.predict(x_test)

In [9]:
metrics.accuracy_score(y_test,pred)

0.2796296296296296

In [19]:
print(classification_report(y_test,pred))

             precision    recall  f1-score   support

          0       1.00      0.43      0.60        47
          1       1.00      0.26      0.42        61
          2       1.00      0.19      0.32        47
          3       0.10      1.00      0.18        44
          4       1.00      0.26      0.42        53
          5       1.00      0.05      0.10        59
          6       1.00      0.41      0.58        59
          7       1.00      0.33      0.49        49
          8       1.00      0.02      0.03        61
          9       1.00      0.07      0.12        60

avg / total       0.93      0.28      0.32       540



In [33]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,pred))

[[20  0  0 27  0  0  0  0  0  0]
 [ 0 16  0 45  0  0  0  0  0  0]
 [ 0  0  9 38  0  0  0  0  0  0]
 [ 0  0  0 44  0  0  0  0  0  0]
 [ 0  0  0 39 14  0  0  0  0  0]
 [ 0  0  0 56  0  3  0  0  0  0]
 [ 0  0  0 35  0  0 24  0  0  0]
 [ 0  0  0 33  0  0  0 16  0  0]
 [ 0  0  0 60  0  0  0  0  1  0]
 [ 0  0  0 56  0  0  0  0  0  4]]


In [11]:
#ques3(b)
model2= SVC(kernel='poly')

In [12]:
model2.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [13]:
pred2=model2.predict(x_test)

In [14]:
metrics.accuracy_score(y_test,pred2)

0.9907407407407407

In [21]:
print(classification_report(y_test,pred))

             precision    recall  f1-score   support

          0       1.00      0.43      0.60        47
          1       1.00      0.26      0.42        61
          2       1.00      0.19      0.32        47
          3       0.10      1.00      0.18        44
          4       1.00      0.26      0.42        53
          5       1.00      0.05      0.10        59
          6       1.00      0.41      0.58        59
          7       1.00      0.33      0.49        49
          8       1.00      0.02      0.03        61
          9       1.00      0.07      0.12        60

avg / total       0.93      0.28      0.32       540



In [34]:
print(confusion_matrix(y_test,pred2))

[[46  0  0  0  1  0  0  0  0  0]
 [ 0 61  0  0  0  0  0  0  0  0]
 [ 0  0 47  0  0  0  0  0  0  0]
 [ 0  0  0 43  0  1  0  0  0  0]
 [ 0  0  0  0 53  0  0  0  0  0]
 [ 0  0  0  0  0 59  0  0  0  0]
 [ 0  0  0  0  0  0 59  0  0  0]
 [ 0  0  0  0  0  0  0 49  0  0]
 [ 0  1  0  0  0  0  0  1 59  0]
 [ 0  0  0  0  0  1  0  0  0 59]]


In [15]:
#ques3(b)
model3= SVC(kernel='linear')

In [16]:
model3.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [17]:
pred3=model3.predict(x_test)


In [18]:
metrics.accuracy_score(y_test,pred3)

0.9796296296296296

In [20]:
print(classification_report(y_test,pred3))

             precision    recall  f1-score   support

          0       1.00      0.98      0.99        47
          1       0.97      1.00      0.98        61
          2       0.98      1.00      0.99        47
          3       1.00      0.98      0.99        44
          4       0.95      1.00      0.97        53
          5       0.97      1.00      0.98        59
          6       1.00      0.98      0.99        59
          7       0.98      0.98      0.98        49
          8       0.97      0.92      0.94        61
          9       1.00      0.97      0.98        60

avg / total       0.98      0.98      0.98       540



In [35]:
print(confusion_matrix(y_test,pred3))


[[46  0  0  0  1  0  0  0  0  0]
 [ 0 61  0  0  0  0  0  0  0  0]
 [ 0  0 47  0  0  0  0  0  0  0]
 [ 0  0  0 43  0  1  0  0  0  0]
 [ 0  0  0  0 53  0  0  0  0  0]
 [ 0  0  0  0  0 59  0  0  0  0]
 [ 0  0  0  0  0  0 58  0  1  0]
 [ 0  0  0  0  1  0  0 48  0  0]
 [ 0  2  1  0  1  0  0  1 56  0]
 [ 0  0  0  0  0  1  0  0  1 58]]


In [24]:
#ques3(d)
model4= SVC(kernel='sigmoid')

In [25]:
model4.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='sigmoid',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [26]:
pred4=model4.predict(x_test)

In [27]:
metrics.accuracy_score(y_test,pred4)

0.08148148148148149

In [28]:
print(classification_report(y_test,pred4))

             precision    recall  f1-score   support

          0       0.00      0.00      0.00        47
          1       0.00      0.00      0.00        61
          2       0.00      0.00      0.00        47
          3       0.08      1.00      0.15        44
          4       0.00      0.00      0.00        53
          5       0.00      0.00      0.00        59
          6       0.00      0.00      0.00        59
          7       0.00      0.00      0.00        49
          8       0.00      0.00      0.00        61
          9       0.00      0.00      0.00        60

avg / total       0.01      0.08      0.01       540



C:\Users\Mehak Sood\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [36]:
print(confusion_matrix(y_test,pred4))

[[ 0  0  0 47  0  0  0  0  0  0]
 [ 0  0  0 61  0  0  0  0  0  0]
 [ 0  0  0 47  0  0  0  0  0  0]
 [ 0  0  0 44  0  0  0  0  0  0]
 [ 0  0  0 53  0  0  0  0  0  0]
 [ 0  0  0 59  0  0  0  0  0  0]
 [ 0  0  0 59  0  0  0  0  0  0]
 [ 0  0  0 49  0  0  0  0  0  0]
 [ 0  0  0 61  0  0  0  0  0  0]
 [ 0  0  0 60  0  0  0  0  0  0]]
